language: node_js
node_js:
  - '8'
sudo: false
jobs:
  include:
    - stage: linting
      name: Run lint
      script: npm run lint
    - stage: Staging deploy
      name: Deploy to AWS staging
      if: branch = master AND commit_message =~ /\[DEPLOY\]/
      env:
        - REACT_APP_DEPLOY_ENV=staging
        - REACT_APP_API_URL=https://boost-api-staging.us-east-1.elasticbeanstalk.com/graphql
      before_deploy:
        - npm run build
      deploy:
        provider: s3
        access_key_id: '$AWS_ACCESS_KEY_ID'
        secret_access_key: '$AWS_SECRET_ACCESS_KEY'
        on:
          branch: master
          condition: '$REACT_APP_DEPLOY_ENV = staging'
        bucket: grantcircles-web-staging
        local_dir: build
        skip_cleanup: true
    - stage: Production deploy
      name: Deploy to AWS production
      if: branch = production
      env:
        - REACT_APP_DEPLOY_ENV=production
        - REACT_APP_API_URL=https://boost-api-production.us-east-1.elasticbeanstalk.com/graphql
      before_deploy:
        - npm run build
      deploy:
        provider: s3
        access_key_id: '$AWS_ACCESS_KEY_ID'
        secret_access_key: '$AWS_SECRET_ACCESS_KEY'
        on:
          branch: production
          condition: '$REACT_APP_DEPLOY_ENV = production'
        bucket: grantcircles-web-production
        local_dir: build
        skip_cleanup: true
env:
  global:
    - secure: tnEz9Hpy3At0Xv6Exwcpmhu3O1V5yFW4YsJZHumT35WoH185nkDp+W5O9O4bKia6VoMquYg3mKh0sdzpV0UpR0kyenAKl/GLa8zoFnFwK+Z1BAX3fD2TYAGlbetcxcUeFTlnfGU4NSJZuvpxft2638jQfDKj2fWHXo42I7A0GH2FaxbCl4u9rO1iurRcCinxzwDGFHepoWit3DqTGenfn5RzeU/sTJGUbYD26Yp8ldn5UBOaq9yw03mwXsycqTr65fowVNY9xY9oy5Wpyr69x52MWZXQ9PEOLstT7Qg6VwDm7439jUkEUP83HbWx3DRuSrYc5lY0D+pHjn4n6a6b1DcDgfhDVXEqeSUiaBIMCD92hmdHq07PH2tCF6rDXswAyplODAkcJ+5DGgPgPXPaj+JqwMtSnVADZ8gUGKhNJsxX/8sEruErX4imixbOGZ96auzHGNTu0pjUkGGI02/F9kAKffNjamlEeaTF3dNMBp9GrL4wQ8kJ/yVBx8+CbGqFK30fv4VrNSUNKsha6WIfAbxQhL1x8lKyLwwDW4HQqFxwIEc9wRzsREICmN2OhuyhSCj/rRW1yoC9/BbG+RxtNsZdtpl7fRu6sRnO6K+NZzl3XUk/cCJ61DUUREGB3t+io7QrwCYNZU+4ttnlvy0pcoL05691vHdbV5uc6r7BYOs=
    - secure: b9hcbwf6q8zCybv9nVvqjLWWVNwV4/RK4ngL0BXXqnX8Jqpus3T8MSNz07Avxw3WD+aEzhGclXJNvutvEvprMByxUOKASGH1XZh/M0YviquzOaOCBcfjHM2omNzuqp0tbzMsO89Uh5aHGaq+FPvKGnCNbtXUxyRh9T0ahGk1duUOTE4RmNt+T1EpepqP5Jh1paZp+ShNO2m6WNXl/ZZ3favZfp6mHtq8nL44jEcpdPrlVhaQRLSl/XCilbVbMwgliptEGAFQt+XJWqtEly7pfPrLveMIbglKxx40dd66F+aWiSIehywcj8ma0PfcrdU4Pj9KXa5u8/xfafPVJ1vDrtawxfRDzAyHNh9jW7dEvYpbZtx7HztKkky28o5GvpFdwqawmcqptsJBdRoT8Be5rZ8vBMbxwhRtNdbU4rzhyyiom6QIn3/5Nh3oubl+8R7mj+xBbSc4ylTBxCbok2wbrm4/kwO5jHH68yBDllKF/WK3IjrBnpHPaVaYEcgf+/BwM/8u7qiSLB+J6QaS8RyXE3rHmvOFlo+ajoPKMR8qTzJC0V4YYN4Zur4uPfjJ3tpOuYBXdqSm5Nx4QQTHfuxWgy1ZK2a01icY+RvLkEATlplvZu2RvTaErTP5IMYGw3vEjOD2OqZFgj0lNxgiTgAioAYQy2lnl4zpioPX9SX8698=
